[workspace]
name                  = "grave pixi workspace"
version               = "2.0.0"
description           = "A workflow for mapping and variant calling aDNA against pangenome graphs"
authors               = ["CormacKinsella <27350062+CormacKinsella@users.noreply.github.com>"]
channels              = ["conda-forge", "bioconda"]
platforms             = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
nextflow              = "==25.10.2"
nf-core               = ">=3.5.1,<4"
nf-test               = ">=0.9.3"

[target.linux-64.dependencies]
vg                    = "==1.70.0"

[feature.apptainer.target.linux-64.dependencies]
apptainer             = "==1.4.5"

[environments]
apptainer             = ["apptainer"]

[tasks]
test-docker           = "nextflow main.nf -profile docker,test -params-file tests/test_graph.yml"
test-apptainer        = "nextflow main.nf -profile apptainer,test -params-file tests/test_graph.yml"
test-singularity      = "nextflow main.nf -profile singularity,test -params-file tests/test_graph.yml"
test-conda            = "nextflow main.nf -profile conda,test -params-file tests/test_graph.yml"
test-docker-linear    = "nextflow main.nf -profile docker,test -params-file tests/test_linear.yml"
test-apptainer-linear = "nextflow main.nf -profile apptainer,test -params-file tests/test_linear.yml"
nftest-docker         = "nf-test test tests/main.nf.test --verbose"
nftest-apptainer      = "nf-test test tests/main.nf.test --verbose --profile apptainer"
nftest-singularity    = "nf-test test tests/main.nf.test --verbose --profile singularity"
debug                 = "nextflow main.nf -profile apptainer,test,debug -params-file tests/test_graph.yml"
help                  = "nextflow main.nf --help"

[activation.env]
NXF_SYNTAX_PARSER     = "v1"
