# Preparation

## Read generation

- Subsampling 100k reads from pre-merged and FASTP processed noirduvelay subsets

```
noirduvelay_30.1.1.fastp.fq.gz
noirduvelay_40.1.1.fastp.fq.gz
noirduvelay_50.1.1.fastp.fq.gz
noirduvelay_60.1.1.fastp.fq.gz
noirduvelay_70.1.1.fastp.fq.gz
```

- seqkit: 2.13.0

```
for i in *fastp.fq.gz; do
    seqkit sample2 --non-deterministic --seq-type dna --number 100000 --two-pass $i > ${i%.fastp.fq.gz}.100k.fastp.fq
done
```

- Committed to the benchmarking branch, in: `tests/data/fastq/benchmarking`

# Step 1: run grave with 5 read sets (lengths 30, 40, 50, 60, 70), in three modes (19/5 and 15/5), & linear
# Note: adding 4 further modes later: 17/5, 17/3, 15/3, 19/3

- output: 10 GAMs (filtered to mapped only, but no other filter), and 5 BAMs from BWA (mapped only, no other filter)
- note removing unmapped != removing MAPQ 0. MAPQ 0 also includes reads with multiple best hits, which we will include for the "lowest" filter threshold.

- we also have the raw GAMS including unmapped, in case you need to check if any reads were lost prior to alignment

```
# Running in commit 41b9783 (2.2.0-pre-release) + some extraneous commits

pixi run nextflow main.nf -profile uppmax -params-file tests/ovis-benchmarking.yml --project uppmax2025-2-425
```

# Step 2: run MAPQ filtering at a range of thresholds

Output:
    - 130 GAMs
    - 15 BAMs

## Graph GAMs

- Since this is exploratory, run a large range of MAPQ filters

```
mapq_values=(5 10 15 20 25 30 35 40 45 50 55 60)

for i in *MAPQ00.gam
    do
        for mapq in "${mapq_values[@]}"
            do
                vg filter --min-mapq "$mapq" -t 16 -x sheep_pangenome_v20260417.d3.gbz -v "$i" > "${i%MAPQ00.gam}MAPQ${mapq}.gam"
            done
    done

for i in noir*MAPQ5.gam; do mv $i ${i%MAPQ5.gam}MAPQ05.gam; done
```

## Linear BAMs

- two MAPQ filters used in aDNA - 20 & 30  - see note below looking into BWA aln MAPQ definitions

for i in *linear.mapped.MAPQ00.bam
    do
        samtools view -b -q 20 $i > ${i%MAPQ00.bam}MAPQ20.bam
    done

for i in *linear.mapped.MAPQ00.bam
    do
        samtools view -b -q 30 $i > ${i%MAPQ00.bam}MAPQ30.bam
    done

```{BWA aln MAPQ definitions}
- `bwase.c` is the script in question
- four possible paths for MAPQ setting, three are fixed values
    - 0: multiple best hits, or unmapped read
    - 25: unique best hit, but at the mismatch threshold
    - 37: unique best hit, no alternative hits
    - the fourth is capped at 23 and degrades based on number of alternative suboptimal hits: unique best hit, but multiple suboptimal hits
```


# Step 3: (GAMS only) - surject to BAM in reference space & refilter for mapped only

## Surject
```
for i in *gam
    do
        vg surject -t 4 -x sheep_pangenome_v20260417.d3.gbz --bam-output $i | \
        samtools sort --threads 4 --output-fmt BAM - > ${i%gam}surjected.sorted.bam
    done
```

## Filter for mapped only (MAPQ > 0)
```
# Running separately so we can also gauge loss rate during surjection, if any
for i in *surjected.sorted.bam; do samtools view --with-header --exclude-flags 4 $i > ${i%bam}mapped.bam; done
```

- 145 BAMs in total

- generated a table of counts per condition at this point (drive: `grave benchmarking counts`)

# Step 4: generate BED format files of the mapped reads

- Output: 145 BED files, with `RAMB1_chr   chromStart   chromEnd   read_name_with_source_coords`

- Running a sanity check that confirmed everything is relative to RAMB1 in the surjected BAMs

```
for i in *surjected.sorted.mapped.bam; do samtools view $i | awk '{print $3}' >> all_targets.txt; done
cat all_targets.txt | sort | uniq
```

```
#Convert the BAMs to BED
for i in *bam; do bedtools bamtobed -i $i > ${i%bam}bed; done
```

```
#aln BEDs already ready:
NC_056054.1     23782   23852   T0_RID945749_S0_CBDTXI010000019.1:57267121-57267190_length:70_mod0100   0       -
```

```
# graph BED structure - not ready (PAN-SN format chrom)
RAMB1#0#NW_024599814.1  9666    9736    T0_RID4246203_S1_CBDTXI010000012.1:1234643-1234712_length:70_mod0000    60      -
```

```
# convert graph beds to format needed for liftover
for i in *surjected.sorted.mapped.bed
    do
        awk 'BEGIN{OFS="\t"} {gsub(/.*#/, "", $1); print}' $i > ${i%bed}converted.bed
    done
```

# Step 5: run liftover against the source assemblies

- Output: 145 lifted BED files

- Step 1, get source assembly (`RAMB1`) into simple header format to match BEDs. `e.g. NC_056054.1`

`sed -i '/^>/s/ .*//' GCF_016772045.2_ARS-UI_Ramb_v3.0_genomic.fna`

- Step 2, get target assembly (`noirduvelay`) into simple header format

```
datasets download genome accession GCA_965363385.1
# unpack, md5sum, etc.

sed -i '/^>/s/ .*//' GCA_965363385.1.fna
```

- Step 3, prepared `nf-chain` input samplesheets and ran (nf-chain v1: BLAT)

- Now also run the same with nf-chain v2: BLAT & minimap2

- Chain coverage looks best in minimap2, and this has the least number of failed lifts on BED lines

- But we now need to compare accuracy, since more lifts doesn't necessarily mean more correct lifts

# Step 6: extract mapping accuracy stats from the liftover results

- Run `accuracy.sh` on the lifted BEDs (found in grave repo benchmarking branch, in `bin/mapping_accuracy.sh`)

- Started by treating accurate as:
    - Correct contig
    - Coordinates have min-70% overlap with true coords
- However, this is problematic since it biases against the very reads we might rescue with a graph - i.e. variant not represented in the linear reference, so the lift is only partial
- Therefore, we now check how much it extends past the true coordinates left or right. New accuracy definition:
    - Correct contig
    - No threshold for overlap is applied
    - A left and right extension tolerance is applied (3bp in this run). Anything that extends beyond this is excluded as inaccurate (partial)

```
for i in *bed
    do
        ./accuracy.sh $i 0 3 3 table | grep -v threshold_pct >> results.tsv
    done
```

- Did some manual processing in google sheets

- For step 7, starting with the minimap2 liftover results, but will run the scripts on BLAT v2 results also.

# Step 7: plots

- Developing in `benchmarking/statistical_plotting`, starting with interactive plots, then moving on to key static plots

- yield plots are the most useful endpoint

- Key static plot: bwa vs graph 15_5 yield

- Did a quick eyeball test of which lift tool is used. Using the BLAT chain file negatively impacted the results in this case, so it was predictable from the summary stats reported by nf-chain


# Step 8: microbial contamination benchmarking

## Data, used that generated by Martiano et al 2020 (https://pubmed.ncbi.nlm.nih.gov/32943086/)

- [30 bp](https://zenodo.org/records/3416364/files/simulation_30_s.fq.gz?download=1)
- [40 bp](https://zenodo.org/records/3416364/files/simulation_40_s.fq.gz?download=1)
- [50 bp](https://zenodo.org/records/3416364/files/simulation_50_s.fq.gz?download=1)
- [60 bp](https://zenodo.org/records/3416364/files/simulation_60_s.fq.gz?download=1)
- [70 bp](https://zenodo.org/records/3416364/files/simulation_70_s.fq.gz?download=1)

```
for i in microbial_*; do fq_count $i; done

microbial_30.fq.gz      100000
microbial_40.fq.gz      100000
microbial_50.fq.gz      100000
microbial_60.fq.gz      100000
microbial_70.fq.gz      100000
```

## Running through the workflow above, steps 1-4 (ending with beds in reference perspective)

- Generated 145 beds containing levels of contamination mapping

- These represent the `before` condition

### Mask microbes (`after` conditions)

- Question to answer: can we run with a lower MAPQ + microbial masking, or do we really need to run with high MAPQ
- End points will be a BED from MCWorkflow, and an output from ncbi-fcs-fx that I need to post-process into a BED
- These need to be intersected with the microbial mapping beds as masking regions

#### Modification of `MCworkflow` -> `cormackinsella/MCWorkflow` (`troubleshooting` branch) (PR'd)

- `troubleshooting` is the code used for our test. `dev` is now the branch for any further commits

    Issues log:
    TODO: add theses as issues on the upstream
    - the custom script is sequential, single threaded. For single assembly (~human/sheep size) run time is acceptable, but if running across many (or large) assemblies, parallelising this into nextflow modules would be preferable
    - merge bam writes many intermediate files that should be streamed
    - check if the removal of intermediate files in exogenous detection is needed, or if streaming could be used instead
    - some fragile filename editing patterns. Workflow needs a robust metadata ingestion instead at the start
    - related, metadata is sporadically updated via map functions, but not stored in a meta object (added into the tuple). Move all of that to the ingestion step
    - Parsing scripts: README could add clarification, or could add some options for QC on the mappings. Setting confidence levels. 1 mapped read is considered a microbial-like hit. How confident are we that the regions are actually microbe-like? From experience, mapping microbe reads to an assembly gets high quality alignments - often spurious

- MCWorkflow identified many regions for masking (though see above - I'm not sure of the confidence level), but almost none of these intersected with our microbial mappings
    - Interestingly, the ONLY intersected microbial mappings were in each `bwa aln` set. No graph mappings whatsoever were intersected out
    - Running theory is that this represents a true microbial contaminant region of the assembly. In the `bwa aln` context, the reads only had one target and their best mapping was to that region. In the graph context, reads like this had a better contaminant region in a different assembly, and mapped there. During surjection that region was not in the reference, so they get lost at this stage.
    - So while graphs are likely more robust to true assembly contamination, they are particularly vulnerable to **spurious mapping**. Here, spurious mappings to actual sheep sequence can occur across a much larger number of assemblies, and when you surject you're laminating all those spurious mappings together

#### `ncbi-fcs-fx`

- Main database is not suitable for a nextflow test profile (470 GB). Needs to be moved into `tempfs`

- `fcs-gx`: Did not identify contamination in the sheep reference. The only hits were to 5 highly repetitive regions, which were flagged as potentially from fish. These are repeat arrays common in eukaryotes

##### Take home point from these two tools

- Take home point: Most likely, the reference genome is pretty clean. Microbial mappings in `grave` or `bwa-aln` are mostly spurious rather than hits to assembly microbial contamination

- NOTE: Effect on sheep reads
    - Based on above results, no need in this case to check the effect
    - If a mask would be applied, we'd need to first check whether it punishes sheep BEDs

# Step 9: plot raw microbial mappings across MAPQ thresholds, aligners, and read lengths

- `MAPQ30` is acceptable for graph mappings, and allows the better k + w setting of 15/5
- However we could potentially be doing better with prefiltering out contamination. If this would be working well, we could lower the default to `MAPQ20`

# Step 10: attempt prefiltering with kraken2 & GTDB

- does prefiltering against GTDB help?
    - https://academic.oup.com/bib/article/26/1/bbae646/7923980
- what do EAGER/DNAHarvester do about contamination?
    - DNAHarvester has an option to run kraken2 on the reads and keep unclassified


# Database

- Testing kraken2 GTDB database (k 35, l 31) (500GB download)
- uncompressed main index is ~650 GB. Docs would need to reflect disk requirements for prefiltering (1.2 TB disk free, of which ~650 can be stored )
- Better to run the download & extract as a pixi task, helper script, or storedir? Needs an md5 check also.

The GTDB database is large. For grave we could probably handle download, but should at least accept a local db that users can download in advance. It would be vital we cache the unpacked database, as each download + unpack will take ~6.5 hrs (with optimisation using aria2 instead of wget). Unpacking not yet optimised.

## Download

-`aria2` on conda-forge is up to date. In testing, `wget` managed 17GB/hour, `aria2` ~90GB/hour

`pixi run aria2c -d . -o "$TAR_FILE" -x 16 -k 100M "$TAR_URL"` # Note x != threads, but parallel connections. This test is running on 2 cores.
    - TODO db should be cached at the process level, e.g. in case an institutional profile uses scratch
    - storeDir?

## RAM use

Normally you'd load the db into RAM, but one this large stalls forever in kraken2, even on a machine with enough RAM. We skip RAM loading and then it runs pretty fast.

- Attempting RAM loading (default) just stalls forever on this size db. `--memory-mapping` needed, and then all samples finished in ~38 minutes, of which around 30 mins was copying the db to node scratch. Thus, in a nextflow context, it might be good to batch samples based on size or number, to copy the db a limited number of times. Each batch would be run in a sequential manner.

## Scratch use

Some institutional profiles copy files into node-local SSD storage for faster operation. Given the db size, this takes ~30 mins alone. Options are:
- disable scratch for kraken2 tasks and run them in parallel (not viable - significant slow down)
- allow scratch but run all samples sequentially in one task, or batches of samples per task - viable option
- allow scratch and run each sample in parallel - not tested, but bad idea: most of the time will be spent copying files

```
# db copy speed:
34:48
 
# classification speed on test files, using node local storage
~4-7 seconds per test file

# classification speed without node local
~6 minutes per test file
```

## Classification performance

- We need a good balance of results filtering that maximises microbial exclusion and minimises endogenous exclusion. There are two key things we can tweak here:
- number of distinct l-mers required to support a classification: raising this seems to reduce endogenous exclusion more than microbial. This makes sense, as we're not classifying reads with one or a few chance hits to the db - only those with consistent distinct matches to the db
- It's read length dependent, so longer reads have more l-mers that can be queried. When increasing this param, shorter reads with fewer l-mers are more severely penalised (more unclassified reads), up until the point they don't have enough l-mers to meet the threshold at all, at which point they're 100% unclassified. This might be ok if by design we are aiming to target modern bacterial contamination rather than ancient microbiome. For this it would be advantageous, as kraken2 would essentially skip short reads, and only longer reads with sufficient classified l-mers would be filtered out.

- The other thing we can tweak is confidence. Kraken2 can calculate a confidence score from it's k-mer hit table for each read. Given a classification to the LCA, it calculates the proportion of k-mer matches to that LCA or it's descendents, over the total number of k-mers (excluding any with ambiguous characters). 
- The issue with this is that this emphasises classification to a particular rank in the db taxonomy. Hits to another bacterial clade outside of the "LCA + descendents" count against the confidence score.
- For our purposes we are more interested in bacterial vs non-bacterial. There is another package (conifer) that can calculate root to leaf confidence scores, such that kmers in the read that are outside the LCA + descendents group, but within ancestral taxonomy ranks of the LCA are counted.
- Some quick testing suggests that this score is more effective for our purposes than the raw kraken2 confidence
- But I guess even this score isn't exactly what we want. Given GTDB is just bacteria and archaea, I wonder if we could calculate a score for total classified k-mers at any rank.


- For benchmarking, we need to explore confidence thresholds. One can use the confidence metric within kraken2 (per read, proportion of read k-mers in LCA or descendents / number of unambiguous k-mers in the read (no ambigious characters)). I think this is dynamic, such that a read failing the confidence threshold will have it's assignment moved up the tree until it passes the threshold. If it hits the root without passing, it's unclassified.
- Alternatively, there is a post-processing tool called `conifer` that can calculate both the LCA style confidence, and a RTL confidence (which includes not just LCA and descendents, but also ancestors)
    - `for i in *out; do conifer -i $i --db ../db/aria2/taxo.k2d --all --both_scores > $i.conifer; done`

- Running kraken2 on each read set & removing any with hits above a certain confidence threshold

- then intersecting with the reads that got lifted to the graph for new accurate/inaccurate counts. For benchmarking we're running it after the fact, in normal operation it would have been first.



## Database choice

- GTDB in a way makes things simple. It will be explicitly for removing bacterial contamination (plus archaea, but we don't expect much). Post-processing optimisation can just focus on minimising endogenous loss and maximising microbial loss, without worrying about taxonomic levels

- If we want to go to another type of database, e.g. RefSeq, then we need to consider a more nuanced parsing that doesn't just focus on classified/not classified, but also on taxon assignments. We would also probably not remove unclassified reads in this case.


## Investigate profile of the current microbial readset

- TODO The microbial dataset isn't pure bacteria, need to run a taxonomy lookup on this to get a better understanding
- If only benchmarking GTDB for bacterial removal, potentially create a better microbial test set


# Step 11 identity filter

- plot for mapq 0, 20, and 30, bwa vs graph 19/5 and 15/5, microbial vs non-microbial
- Initial eyeballing for 30 bp reads around the 0.8 to 0.85 mark suggests that for sheep data AT RELEVANT MAPQs, it has negligible effect on the yield of accurate reads, and a very minor reduction in inaccurate reads (but majority removed are inaccurate)
- jumping up to .9, it starts to be majority accurate removed
- longer reads are more robust to removal than short. But we're still talking small effect sizes for short reads.
- unfortunately does not appear to have a disproportionate filtering effect on microbial reads, which is what we were hoping for. I think we can leave it off by default.
- take home point: identity filter can be left in the code as a niche filter, but does not replace MAPQ generally, or really add to it.
- TODO: For example, it might serve as a replacement filter for ultra-short reads, where MAPQ is depressed due to high numbers of secondary alignments, and we lose good alignments. In this case, we should assess whether the identity filter alone can filter for accurate reads without applying MAPQ
- For longer reads I don't currently seewhere it would add value
- take home point 2: default off, default 0.85


# Remaining tasks

- can identity filter replace mapq for e.g. 30 bp reads and improve yield?
- can we improve the situation for 30bp reads?
- microbial prefiltering to achieve MAPQ 20-25 default


